import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.js';

export const LoginPage: React.FC = () => {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(null); try { await login(username,password); navigate('/',{replace:true}); } catch (err) { setError(err instanceof Error ? err.message : 'Đăng nhập thất bại.'); } finally { setLoading(false); } };
  return <div className="login-page"><main className="login-card"><section className="login-brand"><span className="material-symbols-outlined">school</span><div><h1>EduSmart</h1><p>Đọc tài liệu học tập và hỏi đáp AI dựa trên đúng nguồn môn học.</p></div></section><section className="login-form"><div><span>WELCOME BACK</span><h2>Đăng nhập</h2><p>Tài khoản được tạo và quản lý bởi Admin.</p></div><form onSubmit={submit}><label>Tên đăng nhập<input autoFocus required value={username} onChange={(e)=>setUsername(e.target.value)} placeholder="Nhập tên đăng nhập"/></label><label>Mật khẩu<div className="password-field"><input required type={showPassword?'text':'password'} value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="••••••••"/><button type="button" onClick={()=>setShowPassword(!showPassword)}><span className="material-symbols-outlined">{showPassword?'visibility_off':'visibility'}</span></button></div></label>{error&&<div className="login-error">{error}</div>}<button className="btn-primary" disabled={loading}>{loading?'Đang đăng nhập...':'Đăng nhập'}</button></form></section></main><style>{`.login-page{min-height:100vh;display:grid;place-items:center;background:#f1f5f9;padding:18px}.login-card{width:min(900px,100%);min-height:520px;display:grid;grid-template-columns:1fr 1fr;background:#fff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden;box-shadow:0 20px 50px rgb(15 23 42/.1)}.login-brand{background:#0f172a;color:#fff;padding:48px;display:flex;flex-direction:column;justify-content:space-between}.login-brand>.material-symbols-outlined{font-size:40px;color:#93c5fd}.login-brand h1{font-size:34px;margin-bottom:10px}.login-brand p{color:#cbd5e1;line-height:1.7}.login-form{padding:48px;display:flex;flex-direction:column;justify-content:center}.login-form>div>span{font-size:10px;font-weight:700;letter-spacing:.1em;color:#2563eb}.login-form h2{font-size:27px;margin:5px 0}.login-form>div>p{color:#64748b;margin-bottom:25px}.login-form form{display:flex;flex-direction:column;gap:16px}.login-form label{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:600;color:#334155}.login-form input{width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:11px}.password-field{position:relative}.password-field button{position:absolute;right:8px;top:7px;color:#64748b}.login-error{padding:9px 11px;background:#fef2f2;color:#b91c1c;border-radius:8px;font-size:13px}.login-form .btn-primary{padding:12px}@media(max-width:700px){.login-card{grid-template-columns:1fr}.login-brand{display:none}.login-form{padding:34px 25px}}`}</style></div>;
};
