import React, { useState } from 'react';
import { useApp } from '../context/AppContext.js';
import { useAuth } from '../context/AuthContext.js';
import { deleteDocument, retryDocument, updateDocument } from '../services/documentApi.js';
import type { IDocument } from '../types/index.js';

const ownerId = (document: IDocument): string | undefined => typeof document.uploadedBy === 'string' ? document.uploadedBy : document.uploadedBy?._id ?? document.uploadedBy?.id;
const statusLabel = { uploaded: 'Đã tải lên', processing: 'Đang xử lý', ready: 'Sẵn sàng', failed: 'Xử lý lỗi' } as const;

export const TeacherDashboard: React.FC = () => {
  const { state, dispatch, refreshDocuments } = useApp();
  const { state: auth } = useAuth();
  const [message, setMessage] = useState<string | null>(null);
  const myId = auth.user?._id ?? auth.user?.id;
  const myDocuments = state.documents.filter((doc) => ownerId(doc) === myId);
  const run = async (action: () => Promise<void>, success: string) => { try { await action(); setMessage(success); await refreshDocuments(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Thao tác thất bại.'); } };
  const edit = async (document: IDocument) => {
    const originalName = prompt('Tên hiển thị tài liệu', document.originalName); if (!originalName) return;
    const chapterTitle = prompt('Tên chương', document.chapterTitle); if (!chapterTitle) return;
    const chapter = Number(prompt('Số chương', String(document.chapter))); if (!Number.isInteger(chapter) || chapter < 0) return;
    await run(async () => { const updated = await updateDocument(document._id, { originalName, chapter, chapterTitle }); dispatch({ type: 'UPDATE_DOCUMENT', payload: updated }); }, 'Đã cập nhật metadata.');
  };

  return <div className="teacher-page">
    <header><div><span>TEACHER WORKSPACE</span><h1>Quản lý nội dung môn học</h1><p>Bạn chỉ có thể upload và quản lý tài liệu của mình trong môn đang được phân công.</p></div><button className="btn-primary" onClick={() => dispatch({ type: 'SET_UPLOAD_MODAL', payload: true })}>Upload tài liệu</button></header>
    {message && <div className="teacher-message">{message}</div>}
    <section className="teacher-metrics"><article><strong>{state.subjects.length}</strong><small>Môn được phân công</small></article><article><strong>{myDocuments.length}</strong><small>Tài liệu của tôi</small></article><article><strong>{myDocuments.filter((doc) => doc.status === 'ready').length}</strong><small>Đã sẵn sàng</small></article><article><strong>{myDocuments.filter((doc) => doc.status === 'failed').length}</strong><small>Cần xử lý</small></article></section>
    <section className="teacher-card"><div className="section-title"><div><h2>Môn học được phân công</h2><p>Admin có thể gán nhiều giảng viên cho cùng một môn.</p></div></div><div className="subject-pills">{state.subjects.map((subject) => <span key={subject._id}><strong>{subject.code}</strong>{subject.name}</span>)}{state.subjects.length === 0 && <p>Chưa được phân công môn học.</p>}</div></section>
    <section className="teacher-card"><div className="section-title"><div><h2>Tài liệu của tôi</h2><p>Tài liệu tự công bố sau khi xử lý thành công.</p></div><button onClick={() => void refreshDocuments()}>Làm mới</button></div><div className="teacher-table"><table><thead><tr><th>Tài liệu</th><th>Môn</th><th>Trạng thái</th><th>Chunks</th><th>Thao tác</th></tr></thead><tbody>{myDocuments.map((document) => <tr key={document._id}><td><strong>{document.originalName}</strong><small>Chương {document.chapter}: {document.chapterTitle}</small>{document.errorMessage && <em>{document.errorMessage}</em>}</td><td>{document.subject}</td><td><span className={`state ${document.status}`}>{statusLabel[document.status]}</span></td><td>{document.totalChunks}</td><td><div className="row-actions"><button onClick={() => void edit(document)}>Sửa</button>{document.status === 'failed' && <button onClick={() => void run(() => retryDocument(document._id), 'Đã chạy lại xử lý.')}>Retry</button>}<button className="danger" disabled={document.status === 'processing'} onClick={() => { if (confirm('Xóa tài liệu và toàn bộ lịch sử chat liên quan?')) void run(() => deleteDocument(document._id).then(() => undefined), 'Đã xóa tài liệu.'); }}>Xóa</button></div></td></tr>)}</tbody></table>{myDocuments.length === 0 && <div className="empty">Bạn chưa upload tài liệu.</div>}</div></section>
    <style>{`.teacher-page{width:100%;max-width:1250px;margin:auto;padding:28px}.teacher-page header{display:flex;align-items:flex-end;justify-content:space-between;border-bottom:1px solid var(--color-outline-variant);padding-bottom:20px}.teacher-page header span{font-size:11px;font-weight:700;letter-spacing:.08em;color:var(--color-primary)}.teacher-page h1{font-size:28px;margin:5px 0}.teacher-page header p,.section-title p{color:#64748b}.teacher-message{margin:14px 0;padding:10px 13px;background:#eff6ff;color:#1e40af;border-radius:8px}.teacher-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.teacher-metrics article,.teacher-card{background:#fff;border:1px solid var(--color-outline-variant);border-radius:12px;padding:18px}.teacher-metrics strong{display:block;font-size:27px}.teacher-metrics small{color:#64748b}.teacher-card{margin-top:14px}.section-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.section-title h2{font-size:17px}.section-title button,.row-actions button{border:1px solid #dbe1e8;background:white;border-radius:7px;padding:6px 9px}.subject-pills{display:flex;gap:8px;flex-wrap:wrap}.subject-pills span{display:flex;gap:7px;padding:9px 11px;border:1px solid #e2e8f0;border-radius:8px;color:#475569}.subject-pills strong{color:#1d4ed8}.teacher-table{overflow:auto}.teacher-table table{width:100%;border-collapse:collapse}.teacher-table th,.teacher-table td{text-align:left;padding:11px;border-bottom:1px solid #eef2f7}.teacher-table td small,.teacher-table td em{display:block;color:#64748b;margin-top:3px}.teacher-table td em{color:#b91c1c}.state{font-size:11px;font-weight:700;padding:4px 7px;border-radius:20px;background:#f1f5f9}.state.ready{background:#ecfdf5;color:#047857}.state.failed{background:#fef2f2;color:#b91c1c}.row-actions{display:flex;gap:5px}.row-actions .danger{color:#b91c1c}.empty{padding:35px;text-align:center;color:#64748b}@media(max-width:800px){.teacher-metrics{grid-template-columns:1fr 1fr}}@media(max-width:560px){.teacher-page{padding:18px}.teacher-page header{align-items:flex-start;gap:14px;flex-direction:column}.teacher-metrics{grid-template-columns:1fr}}`}</style>
  </div>;
};
